### ISSUE TITLE
fixuid breaks image

### ISSUE THREAD

**Issue by samsaptidev** [sethforprivacy/simple-monerod-docker#63] opened 2022-07-25 15:04 UTC
After merging #62, my logs look like this:

```console
$ docker-compose logs -f monerod
monerod  | /usr/local/bin/fixuid: line 1: syntax error: unterminated quoted string
monerod  | /usr/local/bin/fixuid: line 1: syntax error: unterminated quoted string
monerod  | /usr/local/bin/fixuid: line 1: syntax error: unterminated quoted string
monerod  | /usr/local/bin/fixuid: line 1: syntax error: unterminated quoted string
monerod  | /usr/local/bin/fixuid: line 1: syntax error: unterminated quoted string
monerod  | /usr/local/bin/fixuid: line 1: syntax error: unterminated quoted string
monerod  | /usr/local/bin/fixuid: line 1: syntax error: unterminated quoted string
monerod  | /usr/local/bin/fixuid: line 1: syntax error: unterminated quoted string
monerod  | /usr/local/bin/fixuid: line 1: syntax error: unterminated quoted string
monerod  | /usr/local/bin/fixuid: line 1: syntax error: unterminated quoted string
monerod exited with code 2
```

Adding `user: "${FIXUID:-1000}:${FIXGID:-1000}"` didn't help either. Image tag [v0.17.3.2](https://hub.docker.com/layers/simple-monerod/sethsimmons/simple-monerod/v0.17.3.2/images/sha256-058391b15de0ecac727e3c029e6b72a316d6eda457964a8adf801422b9717b74?context=explore) works as expected.

This is on a Raspberry Pi 4B.

**Comment by sethforprivacy** [comment] 2022-07-25 15:25
Ahhh, maybe fixuid doesn't support ARM on that binary... I'll work on a solution.

**Comment by sethforprivacy** [comment] 2022-07-25 15:32
Pushed a fix in https://github.com/sethforprivacy/simple-monerod-docker/commit/bb0836ffea6b0bce35981d29b121ab8dcd7f88de, please test ASAP once the image is pushed as I don't have an ARM device to test on.

**Comment by sethforprivacy** [comment] 2022-07-25 18:05
@samsaptidev New image is pushed, please test and report back!

**Comment by samsaptidev** [comment] 2022-07-25 18:32
@sethforprivacy Still doesn't work :(

**Comment by samsaptidev** [comment] 2022-07-25 20:43
@sethforprivacy Yes, same error, I did pull the latest image.

```console
$ docker-compose down
$ docker-compose pull
$ docker-compose up -d
```

**Comment by samsaptidev** [comment] 2022-07-25 20:56
I do have an idea about what could be wrong though. I'll paste a diff below:

```diff
diff --git a/entrypoint.sh b/entrypoint.sh
index 2223794..8826e49 100644
--- a/entrypoint.sh
+++ b/entrypoint.sh
@@ -1,16 +1,16 @@
-#!/bin/ash
+#!/bin/sh
 # Credit for the bulk of this entrypoint script goes to cornfeedhobo
 # Source is https://github.com/cornfeedhobo/docker-monero/blob/master/entrypoint.sh
 set -e
 
 # Set require --non-interactive flag
-set -- monerod --non-interactive "$@"
+set -- "monerod" "--non-interactive" "$@"
 
 # Configure NUMA if present for improved performance
-numa='numactl --interleave=all'
-if $numa true &> /dev/null; then
-	set -- $numa "$@"
+if command -v numactl > /dev/null 2>&1; then
+    numa="numactl --interleave=all"
+	set -- "$numa" "$@"
 fi
 # Start the daemon using fixuid
 # to adjust permissions if needed
-exec fixuid -q "$@"
\ No newline at end of file
+exec fixuid -q "$@"
```

Basically, I've quoted some variables and made the `entrypoint.sh` script POSIX compliant.

**Comment by sethforprivacy** [comment] 2022-07-26 13:11
> I do have an idea about what could be wrong though. I'll paste a diff below:
> 
> 
> 
> ```diff
> 
> diff --git a/entrypoint.sh b/entrypoint.sh
> 
> index 2223794..6163c6e 100644
> 
> --- a/entrypoint.sh
> 
> +++ b/entrypoint.sh
> 
> @@ -1,16 +1,16 @@
> 
> -#!/bin/ash
> 
> +#!/bin/sh
> 
>  # Credit for the bulk of this entrypoint script goes to cornfeedhobo
> 
>  # Source is https://github.com/cornfeedhobo/docker-monero/blob/master/entrypoint.sh
> 
>  set -e
> 
>  
> 
>  # Set require --non-interactive flag
> 
> -set -- monerod --non-interactive "$@"
> 
> +set -- "monerod" "--non-interactive" "$@"
> 
>  
> 
>  # Configure NUMA if present for improved performance
> 
> -numa='numactl --interleave=all'
> 
> -if $numa true &> /dev/null; then
> 
> -	set -- $numa "$@"
> 
> +if command -v numactl >/dev/null 2>&1; then
> 
> +    numa="numactl --interleave=all"
> 
> +    set -- "$numa" "$@"
> 
>  fi
> 
>  # Start the daemon using fixuid
> 
>  # to adjust permissions if needed
> 
> -exec fixuid -q "$@"
> 
> \ No newline at end of file
> 
> +exec fixuid -q "$@"
> 
> ```
> 
> 
> 
> Basically, I've quoted some variables/strings and made the `entrypoint.sh` script POSIX compliant.
> 
> 

Great catch, if that works for you please PR it! 

I'm traveling but can approve the PR and let the automatic builds push it.

**Comment by samsaptidev** [comment] 2022-07-26 16:59
@sethforprivacy I've submitted a PR (#64).

**Comment by sethforprivacy** [comment] 2022-07-26 19:13
> @sethforprivacy I've submitted a PR (#64).

Thanks so much! Approved and running a test workflow before pushing a new image with the changes.

**Comment by sethforprivacy** [comment] 2022-07-26 22:12
New image is building via https://github.com/sethforprivacy/simple-monerod-docker/runs/7529308323?check_suite_focus=true, should push within the next hour if you don't mind testing then.

**Comment by sethforprivacy** [comment] 2022-07-26 23:30
@samsaptidev new image is live and working properly for me on amd64, please test on arm64 when you get the chance!

**Comment by vdo** [comment] 2022-07-27 17:09
I just tried to install xmr.sh in a RPi and I'm getting this bug (both with `latest` and `v0.18.0.0`):

``` 
root@raspberrypi:/opt/xmr.sh# docker logs monerod
/usr/local/bin/fixuid: line 1: syntax error: unterminated quoted string
/usr/local/bin/fixuid: line 1: syntax error: unterminated quoted string
/usr/local/bin/fixuid: line 1: syntax error: unterminated quoted string
/usr/local/bin/fixuid: line 1: syntax error: unterminated quoted string
/usr/local/bin/fixuid: line 1: syntax error: unterminated quoted string
/usr/local/bin/fixuid: line 1: syntax error: unterminated quoted string
/usr/local/bin/fixuid: line 1: syntax error: unterminated quoted string
/usr/local/bin/fixuid: line 1: syntax error: unterminated quoted string
/usr/local/bin/fixuid: line 1: syntax error: unterminated quoted string
root@raspberrypi:/opt/xmr.sh# docker ps | grep monerod
fbfbbfe78312   sethsimmons/simple-monerod:v0.18.0.0   "/entrypoint.sh --pu…"   58 seconds ago   Restarting (2) 19 seconds ago                                                                                  monerod
```

**Comment by sethforprivacy** [comment] 2022-07-27 17:19
@vdo investigating the cause of this, I'm not sure why this would only happen on the ARM Alpine image at this point. If you have any tips I'm all ears as well!

**Comment by vdo** [comment] 2022-07-27 17:26
I found the cause, the binary is not ARM64, but x86-64, probably the arch is not correctly detected in the `Dockerfile`. From within the image:
```
/home/monero # fixuid
/usr/local/bin/fixuid: line 1: syntax error: unterminated quoted string
/home/monero # file /usr/local/bin/fixuid
/usr/local/bin/fixuid: setuid ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, Go BuildID=1125EmpZ5ZHTb2ews0ry/INFCnSqDFs1vjNZcIhEh/W8-_OIII-6_sSgui7YlP/uYp1bpCz_s4lay4rDCGl, not stripped
```

**Comment by vdo** [comment] 2022-07-27 17:42
This could related with buildx: 

https://github.com/docker/buildx/issues/1234

**Comment by sethforprivacy** [comment] 2022-07-27 17:53
Ahh, so even my change didn't pull the right binary... Thanks for digging into it, will keep doing the same and see if I can push a fix.

**Comment by sethforprivacy** [comment] 2022-07-27 18:11
Idk if it's this simple or not, but I was missing an ARG in the final image build for TARGETARCH:

https://github.com/sethforprivacy/simple-monerod-docker/commit/7623618220fbf6597eb6eccbdf8830f082a373ea

That may (or may not) fix it, but needed to be added anyways. If you can test with a local image build please do so @vdo.

**Comment by vdo** [comment] 2022-07-27 18:20
Ok I'm building it locally with buildx to see if the issue is solved in the emulated container

**Comment by sethforprivacy** [comment] 2022-07-27 18:38
It seems to be grabbing arm64 binaries properly on the ARM image now: https://github.com/sethforprivacy/simple-monerod-docker/runs/7546320235?check_suite_focus=true#step:11:285

**Comment by vdo** [comment] 2022-07-27 19:38
Unfortunately there's no way (afaik) to post-build load an image from another arch using buildx... so I will just wait until it finishes to confirm it works on the RPi

**Comment by sethforprivacy** [comment] 2022-07-27 20:29
@vdo @samsaptidev new image is pushed, please test and report back when you can!

**Comment by vdo** [comment] 2022-07-27 20:38
Works now, up and syncing :cocktail:

**Comment by sethforprivacy** [comment] 2022-07-27 20:46
Awesome! Closing this out, thanks so much for the help finding the root cause here :D

**Closed by sethforprivacy** 2022-07-27 20:46 UTC

**Comment by samsaptidev** [comment] 2022-07-29 19:16
Sorry I'm late to the party. Can confirm it works now, thanks @vdo and @sethforprivacy!

**Comment by sethforprivacy** [comment] 2022-07-29 21:44
> Sorry I'm late to the party. Can confirm it works now, thanks @vdo and @sethforprivacy!

Np, thanks for validating!

**Comment by samsapti** [comment] 2022-10-11 07:23
@sethforprivacy That would definitely be the cause. I'm positive this fixes it. I don't have time to test right now unfortunately.

On July 27, 2022 8:11:14 PM GMT+02:00, Seth For Privacy ***@***.***> wrote:
>Idk if it's this simple or not, but I was missing an ARG in the final image build for TARGETARCH:
>
>https://github.com/sethforprivacy/simple-monerod-docker/commit/7623618220fbf6597eb6eccbdf8830f082a373ea
>
>That may (or may not) fix it, but needed to be added anyways. If you can test with a local image build please do so @vdo.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/sethforprivacy/simple-monerod-docker/issues/63#issuecomment-1197122228
>You are receiving this because you were mentioned.
>
>Message ID: ***@***.***>

--
https://samsapti.dev
